# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Video title')),
                ('title_uk', models.CharField(max_length=200, null=True, verbose_name='Video title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Video title')),
                ('title_de', models.CharField(max_length=200, null=True, verbose_name='Video title')),
                ('title_pl', models.CharField(max_length=200, null=True, verbose_name='Video title')),
                ('notes', models.TextField(verbose_name='News text')),
                ('notes_uk', models.TextField(null=True, verbose_name='News text')),
                ('notes_en', models.TextField(null=True, verbose_name='News text')),
                ('notes_de', models.TextField(null=True, verbose_name='News text')),
                ('notes_pl', models.TextField(null=True, verbose_name='News text')),
                ('vid', models.CharField(blank=True, max_length=800, verbose_name='Embedded YouTube URL to video')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published date')),
            ],
            options={
                'verbose_name_plural': 'Band videos',
                'verbose_name': 'Band video',
            },
        ),
    ]
