# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='sc_link',
            field=models.URLField(blank=True, max_length=400, verbose_name='Embedded URL to albom at SoundCloud'),
        ),
    ]
