# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_sc_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='sc_link',
            field=models.CharField(blank=True, max_length=800, verbose_name='Embedded URL to albom at SoundCloud'),
        ),
    ]
