# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170316_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.CharField(max_length=30, verbose_name='Service name')),
                ('linklink', models.URLField(blank=True, max_length=400, verbose_name="Link to album's page on the service")),
                ('linkicon', models.ImageField(upload_to='', verbose_name="Service's icon")),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
            options={
                'verbose_name': 'Links to buy or listen to album',
                'verbose_name_plural': 'Links to buy or listen to album',
            },
        ),
    ]
