# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_albumlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumlinks',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='music.Album', verbose_name='album'),
        ),
        migrations.AlterField(
            model_name='albumlinks',
            name='linkicon',
            field=models.ImageField(blank=True, upload_to='', verbose_name="Service's icon"),
        ),
        migrations.AlterField(
            model_name='albumlinks',
            name='linkname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Service name'),
        ),
    ]
