# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170323_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumlinks',
            name='album',
            field=models.CharField(max_length=400),
        ),
    ]
