# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20170323_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumLinks',
        ),
    ]
