# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_delete_albumlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=400)),
                ('linkname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Service name')),
                ('linklink', models.URLField(blank=True, max_length=400, verbose_name="Link to album's page on the service")),
                ('linkicon', models.ImageField(blank=True, upload_to='', verbose_name="Service's icon")),
            ],
            options={
                'verbose_name': 'Links to buy or listen to album',
                'verbose_name_plural': 'Links to buy or listen to album',
            },
        ),
    ]
