# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20170323_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Service name')),
                ('linklink', models.URLField(blank=True, max_length=400, verbose_name="Link to album's page on the service")),
                ('linkicon', models.ImageField(blank=True, upload_to='', verbose_name="Service's icon")),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='music.Album', verbose_name='album')),
            ],
            options={
                'verbose_name': 'Links to buy or listen to album',
                'verbose_name_plural': 'Links to buy or listen to album',
            },
        ),
    ]
