# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170120_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='brief_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=400, verbose_name='Крткй зглвк для'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фоточка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='blog_content',
            field=models.TextField(verbose_name='Текст новини'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Написано, дата'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубліковано, дата'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
    ]
