# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170124_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': "Band's news", 'verbose_name_plural': "Band's news"},
        ),
    ]
