# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20170307_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Band news', 'verbose_name_plural': 'Band news'},
        ),
    ]
