# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20170309_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blog_content_de',
            field=models.TextField(null=True, verbose_name='News text'),
        ),
        migrations.AddField(
            model_name='article',
            name='blog_content_en',
            field=models.TextField(null=True, verbose_name='News text'),
        ),
        migrations.AddField(
            model_name='article',
            name='blog_content_pl',
            field=models.TextField(null=True, verbose_name='News text'),
        ),
        migrations.AddField(
            model_name='article',
            name='blog_content_uk',
            field=models.TextField(null=True, verbose_name='News text'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_de',
            field=models.CharField(max_length=200, null=True, verbose_name='News title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='News title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_pl',
            field=models.CharField(max_length=200, null=True, verbose_name='News title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='News title'),
        ),
    ]
