# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageInitialSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandsname', models.TextField(verbose_name="Band's Name")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name="Band's Logo")),
                ('phone', models.CharField(max_length=15, verbose_name='Management Phone')),
                ('email', models.CharField(max_length=30, verbose_name='Management Email')),
                ('skype', models.CharField(max_length=30, verbose_name='Management Skype')),
            ],
            options={
                'verbose_name': "Band's settings",
                'verbose_name_plural': "Band's settings",
            },
        ),
    ]
