# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageinitialsettings',
            name='rider',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Technical Rider'),
        ),
    ]
