# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepageinitialsettings_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageinitialsettings',
            name='homepage_pic_top',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фоточка'),
        ),
    ]
