# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepageinitialsettings_homepage_pic_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.CharField(max_length=30, verbose_name='Service name')),
                ('linklink', models.URLField(blank=True, max_length=400, verbose_name="Link to band's page on the service")),
                ('linkicon', models.ImageField(upload_to='', verbose_name="Service's icon")),
            ],
            options={
                'verbose_name_plural': "Site's settings",
                'verbose_name': "Site's settings",
            },
        ),
        migrations.AlterModelOptions(
            name='homepageinitialsettings',
            options={'verbose_name': "Site's settings", 'verbose_name_plural': "Site's settings"},
        ),
        migrations.AddField(
            model_name='homepageinitialsettings',
            name='homepage_pic_bottom',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Homepage Bottom Pictire'),
        ),
        migrations.AlterField(
            model_name='homepageinitialsettings',
            name='bandsname',
            field=models.CharField(max_length=200, verbose_name="Band's Name"),
        ),
        migrations.AlterField(
            model_name='homepageinitialsettings',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Management Email'),
        ),
        migrations.AlterField(
            model_name='homepageinitialsettings',
            name='homepage_pic_top',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Homepage Top Pictire'),
        ),
    ]
