# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170220_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linksbar',
            options={'verbose_name': "Band's links, social buttons etc", 'verbose_name_plural': "Band's links, social buttons etc"},
        ),
        migrations.AddField(
            model_name='homepageinitialsettings',
            name='newspage_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Homepage Bottom Pictire'),
        ),
    ]
