# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170220_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageinitialsettings',
            options={'verbose_name': "Site's initial settings", 'verbose_name_plural': "Site's initial settings"},
        ),
        migrations.AddField(
            model_name='homepageinitialsettings',
            name='albumspage_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Newspage Pictire'),
        ),
        migrations.AddField(
            model_name='homepageinitialsettings',
            name='musicpage_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Newspage Pictire'),
        ),
        migrations.AddField(
            model_name='homepageinitialsettings',
            name='showspage_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Newspage Pictire'),
        ),
        migrations.AlterField(
            model_name='homepageinitialsettings',
            name='newspage_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Newspage Pictire'),
        ),
    ]
