# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170222_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageinitialsettings',
            name='albumspage_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Albumspage Pictire'),
        ),
        migrations.AlterField(
            model_name='homepageinitialsettings',
            name='musicpage_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Musicpage Pictire'),
        ),
        migrations.AlterField(
            model_name='homepageinitialsettings',
            name='showspage_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Showspage Pictire'),
        ),
    ]
