# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170222_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageinitialsettings',
            name='bandsname',
            field=models.CharField(max_length=200, verbose_name='Band Name'),
        ),
        migrations.AlterField(
            model_name='homepageinitialsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Band Logo'),
        ),
    ]
