# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170309_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageinitialsettings',
            name='bandsname_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Band Name'),
        ),
        migrations.AddField(
            model_name='homepageinitialsettings',
            name='bandsname_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Band Name'),
        ),
        migrations.AddField(
            model_name='homepageinitialsettings',
            name='bandsname_pl',
            field=models.CharField(max_length=200, null=True, verbose_name='Band Name'),
        ),
        migrations.AddField(
            model_name='homepageinitialsettings',
            name='bandsname_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Band Name'),
        ),
    ]
