# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170320_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techriderimg',
            options={'verbose_name': 'Technical Rider Image - Up to three images supported', 'verbose_name_plural': 'Technical Rider Images'},
        ),
    ]
