# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170320_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_img', models.ImageField(blank=True, upload_to='', verbose_name='Carousel Img')),
                ('comment', models.CharField(blank=True, max_length=400, null=True, verbose_name='Comment to img')),
            ],
            options={
                'verbose_name': 'Homepage Carousel Image',
                'verbose_name_plural': 'Homepage Carousel Images',
            },
        ),
    ]
