# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_carouselimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimg',
            name='comment_de',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Comment to img'),
        ),
        migrations.AddField(
            model_name='carouselimg',
            name='comment_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Comment to img'),
        ),
        migrations.AddField(
            model_name='carouselimg',
            name='comment_pl',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Comment to img'),
        ),
        migrations.AddField(
            model_name='carouselimg',
            name='comment_uk',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Comment to img'),
        ),
        migrations.AddField(
            model_name='techriderimg',
            name='comment_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rider Specification'),
        ),
        migrations.AddField(
            model_name='techriderimg',
            name='comment_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rider Specification'),
        ),
        migrations.AddField(
            model_name='techriderimg',
            name='comment_pl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rider Specification'),
        ),
        migrations.AddField(
            model_name='techriderimg',
            name='comment_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rider Specification'),
        ),
    ]
