# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170320_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageinitialsettings',
            name='homepage_pic_bottom',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Videospage Pictire'),
        ),
    ]
