# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=200, verbose_name='City, Venue')),
                ('show_date', models.DateField(verbose_name='Date of Show')),
                ('show_info', models.TextField(verbose_name='Show Info')),
                ('affiche', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Affiche')),
                ('tickets_link', models.TextField(blank=True, verbose_name='Link to buy tickets')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Опубліковано, дата')),
            ],
            options={
                'verbose_name_plural': "Band's shows",
                'verbose_name': "Band's shows",
            },
        ),
    ]
