# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='tickets_link',
            field=models.URLField(blank=True, max_length=400, verbose_name='Link to buy tickets'),
        ),
    ]
