# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20170220_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': 'Band shows', 'verbose_name_plural': 'Band shows'},
        ),
    ]
