# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20170309_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='show_info_de',
            field=models.TextField(null=True, verbose_name='Show Info'),
        ),
        migrations.AddField(
            model_name='poster',
            name='show_info_en',
            field=models.TextField(null=True, verbose_name='Show Info'),
        ),
        migrations.AddField(
            model_name='poster',
            name='show_info_pl',
            field=models.TextField(null=True, verbose_name='Show Info'),
        ),
        migrations.AddField(
            model_name='poster',
            name='show_info_uk',
            field=models.TextField(null=True, verbose_name='Show Info'),
        ),
        migrations.AddField(
            model_name='poster',
            name='venue_de',
            field=models.CharField(max_length=200, null=True, verbose_name='City, Venue'),
        ),
        migrations.AddField(
            model_name='poster',
            name='venue_en',
            field=models.CharField(max_length=200, null=True, verbose_name='City, Venue'),
        ),
        migrations.AddField(
            model_name='poster',
            name='venue_pl',
            field=models.CharField(max_length=200, null=True, verbose_name='City, Venue'),
        ),
        migrations.AddField(
            model_name='poster',
            name='venue_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='City, Venue'),
        ),
    ]
